### ISSUE TITLE
Undefined config in this.ctx

### ISSUE THREAD

**Issue by bliu13** [AriPerkkio/vitest-sonar-reporter#36]
package.json
```
{
  "exports": "./index.js",
  "node": ">=14.16",
  "scripts": {
    "lint": "eslint --fix --cache ./ || true",
    "test": "vitest --watch",
    "testCoverage": "vitest run --coverage --passWithNoTests --reporter verbose",
    "sonar": "node ./sonar.js",
    "testanalyze": "vitest run --coverage --passWithNoTests --reporter verbose && node ./sonar.js",
    "webstorm-integration": "vitest --watch --reporter=dot --reporter=json --outputFile=.vitest-result.json"
  },
  "type": "module",
  "devDependencies": {
    "@vitest/coverage-c8": "^0.25.4",
    "c8": "^7.12.0",
    "eslint": "^8.29.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "msw": "^0.49.1",
    "sonarqube-scanner": "^2.9.1",
    "vite": "^3.2.5",
    "vitest": "^0.25.4",
    "vitest-sonar-reporter": "^0.3.3"
  }
}
```

vite.config.ts
```
import { configDefaults, defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    exclude: configDefaults.exclude,
    testTimeout: 30000,
    reporters: 'vitest-sonar-reporter',
    outputFile: 'coverage/sonar-report.xml',
    coverage: {
      reporter: ['lcov']
    }
  },
})
```

Error
```
SonarQube report written to /path/to/project/coverage/sonar-report.xml
file:///path/to/project/node_modules/vitest-sonar-reporter/dist/sonar-reporter.js:19
        const reportFile = resolve(this.ctx.config.root, this.outputFile);
                                            ^

TypeError: Cannot read properties of undefined (reading 'config')
    at SonarReporter.onFinished (file:///path/to/project/node_modules/vitest-sonar-reporter/dist/sonar-reporter.js:19:45)
    at file:///path/to/project/node_modules/vitest/dist/chunk-vite-node-externalize.ddcbafa3.js:10918:51
    at Array.map (<anonymous>)
    at Vitest.report (file:///path/to/project/node_modules/vitest/dist/chunk-vite-node-externalize.ddcbafa3.js:10916:38)
    at file:///path/to/project/node_modules/vitest/dist/chunk-vite-node-externalize.ddcbafa3.js:10753:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Vitest.runFiles (file:///path/to/project/node_modules/vitest/dist/chunk-vite-node-externalize.ddcbafa3.js:10760:12)
    at async Vitest.start (file:///path/to/project/node_modules/vitest/dist/chunk-vite-node-externalize.ddcbafa3.js:10673:5)

Node.js v19.2.0
```

**Comment by AriPerkkio** [comment]
@bliu13 could you test if this error comes up with `vitest@0.24.3`?

```sh
npm install -E vitest@0.24.3
```

**Comment by bliu13** [comment]
Sorry, I've been away. For some reason I am not able to reproduce the issue now. I'll reopen if I come across a reliable way to replicate the issue.
